bronze_validations = {
    "non_negative_age": "AGE >= 0 or AGE == -9",
    "valid_age_type": "cast(AGE as int) == AGE",
    "valid_year_type": "cast(YEAR as int) == YEAR",
    "valid_caseid_type": "cast(CASEID as long) == CASEID",
    "valid_educ_values": "EDUC >= -9",
    "valid_ethnic_values": "ETHNIC >= -9",
    "valid_race_values": "RACE >= -9",
    "valid_gender_values": "GENDER >= -9",
    "valid_sphservice_values": "SPHSERVICE >= -9",
    "valid_cmpservice_values": "CMPSERVICE >= -9",
    "valid_opiservice_values": "OPISERVICE >= -9",
    "valid_rtcservice_values": "RTCSERVICE >= -9",
    "valid_ijsservice_values": "IJSSERVICE >= -9",
    "valid_mh1_values": "MH1 >= -9",
    "valid_mh2_values": "MH2 >= -9",
    "valid_mh3_values": "MH3 >= -9",
    "valid_sub_values": "SUB >= -9",
    "valid_marstat_values": "MARSTAT >= -9",
    "valid_smised_values": "SMISED >= -9",
    "valid_sap_values": "SAP >= -9",
    "valid_employ_values": "EMPLOY >= -9",
    "valid_detnlf_values": "DETNLF >= -9",
    "valid_veteran_values": "VETERAN >= -9",
    "valid_livarag_values": "LIVARAG >= -9",
    "valid_nummhs_values": "NUMMHS >= -9",
    "valid_traustref_values": "TRAUSTREFLG >= -9",
    "valid_anxiety_values": "ANXIETYFLG >= -9",
    "valid_adhd_values": "ADHDFLG >= -9",
    "valid_conduct_values": "CONDUCTFLG >= -9",
    "valid_delirdem_values": "DELIRDEMFLG >= -9",
    "valid_bipolar_values": "BIPOLARFLG >= -9",
    "valid_depress_values": "DEPRESSFLG >= -9",
    "valid_odd_values": "ODDFLG >= -9",
    "valid_pdd_values": "PDDFLG >= -9",
    "valid_person_values": "PERSONFLG >= -9",
    "valid_schizo_values": "SCHIZOFLG >= -9",
    "valid_alcsub_values": "ALCSUBFLG >= -9",
    "valid_otherdis_values": "OTHERDISFLG >= -9",
    "valid_statefip_values": "STATEFIP >= -9",
    "valid_division_values": "DIVISION >= -9",
    "valid_region_values": "REGION >= -9",
}

silver_1_validation = {
    "non_negative_age": "AGE >= 0 or AGE == -9",
    "valid_age_type": "cast(AGE as int) == AGE",
    "valid_year_type": "cast(YEAR as int) == YEAR",
    "valid_caseid_type": "cast(CASEID as long) == CASEID",
    "valid_educ_values": "EDUC >= -9",
    "valid_ethnic_values": "ETHNIC >= -9",
    "valid_race_values": "RACE >= -9",
    "valid_gender_values": "GENDER >= -9",
    "valid_sphservice_values": "SPHSERVICE >= -9",
    "valid_cmpservice_values": "CMPSERVICE >= -9",
    "valid_opiservice_values": "OPISERVICE >= -9",
    "valid_rtcservice_values": "RTCSERVICE >= -9",
    "valid_ijsservice_values": "IJSSERVICE >= -9",
    "valid_mh1_values": "MH1 >= -9",
    "valid_mh2_values": "MH2 >= -9",
    "valid_mh3_values": "MH3 >= -9",
    "valid_sub_values": "SUB >= -9",
    "valid_marstat_values": "MARSTAT >= -9",
    "valid_smised_values": "SMISED >= -9",
    "valid_sap_values": "SAP >= -9",
    "valid_employ_values": "EMPLOY >= -9",
    "valid_detnlf_values": "DETNLF >= -9",
    "valid_veteran_values": "VETERAN >= -9",
    "valid_livarag_values": "LIVARAG >= -9",
    "valid_nummhs_values": "NUMMHS >= -9",
    "valid_traustref_values": "TRAUSTREFLG >= -9",
    "valid_anxiety_values": "ANXIETYFLG >= -9",
    "valid_adhd_values": "ADHDFLG >= -9",
    "valid_conduct_values": "CONDUCTFLG >= -9",
    "valid_delirdem_values": "DELIRDEMFLG >= -9",
    "valid_bipolar_values": "BIPOLARFLG >= -9",
    "valid_depress_values": "DEPRESSFLG >= -9",
    "valid_odd_values": "ODDFLG >= -9",
    "valid_pdd_values": "PDDFLG >= -9",
    "valid_person_values": "PERSONFLG >= -9",
    "valid_schizo_values": "SCHIZOFLG >= -9",
    "valid_alcsub_values": "ALCSUBFLG >= -9",
    "valid_otherdis_values": "OTHERDISFLG >= -9",
    "valid_statefip_values": "STATEFIP >= -9",
    "valid_division_values": "DIVISION >= -9",
    "valid_region_values": "REGION >= -9",
}

silver_2_validation = {
    "non_negative_age": "AGE >= 0 or AGE == -9",
    "valid_age_type": "cast(AGE as int) == AGE",
    "valid_year_type": "cast(YEAR as int) == YEAR",
    "valid_caseid_type": "cast(CASEID as long) == CASEID",
    "valid_educ_values": "EDUC >= -9",
    "valid_ethnic_values": "ETHNIC >= -9",
    "valid_race_values": "RACE >= -9",
    "valid_gender_values": "GENDER >= -9",
    "valid_sphservice_values": "SPHSERVICE >= -9",
    "valid_cmpservice_values": "CMPSERVICE >= -9",
    "valid_opiservice_values": "OPISERVICE >= -9",
    "valid_rtcservice_values": "RTCSERVICE >= -9",
    "valid_ijsservice_values": "IJSSERVICE >= -9",
    "valid_mh1_values": "MH1 >= -9",
    "valid_mh2_values": "MH2 >= -9",
    "valid_mh3_values": "MH3 >= -9",
    "valid_sub_values": "SUB >= -9",
    "valid_marstat_values": "MARSTAT >= -9",
    "valid_smised_values": "SMISED >= -9",
    "valid_sap_values": "SAP >= -9",
    "valid_employ_values": "EMPLOY >= -9",
    "valid_detnlf_values": "DETNLF >= -9",
    "valid_veteran_values": "VETERAN >= -9",
    "valid_livarag_values": "LIVARAG >= -9",
    "valid_nummhs_values": "NUMMHS >= -9",
    "valid_traustref_values": "TRAUSTREFLG >= -9",
    "valid_anxiety_values": "ANXIETYFLG >= -9",
    "valid_adhd_values": "ADHDFLG >= -9",
    "valid_conduct_values": "CONDUCTFLG >= -9",
    "valid_delirdem_values": "DELIRDEMFLG >= -9",
    "valid_bipolar_values": "BIPOLARFLG >= -9",
    "valid_depress_values": "DEPRESSFLG >= -9",
    "valid_odd_values": "ODDFLG >= -9",
    "valid_pdd_values": "PDDFLG >= -9",
    "valid_person_values": "PERSONFLG >= -9",
    "valid_schizo_values": "SCHIZOFLG >= -9",
    "valid_alcsub_values": "ALCSUBFLG >= -9",
    "valid_otherdis_values": "OTHERDISFLG >= -9",
    "valid_statefip_values": "STATEFIP >= -9",
    "valid_division_values": "DIVISION >= -9",
    "valid_region_values": "REGION >= -9",
    "valid_nummhs_normalized": "NUMMHS_normalized is not null",
    "valid_nummhs_standardized": "NUMMHS_standardized is not null",
}

silver_3_validation = {
    "non_negative_age": "AGE >= 0 or AGE == -9",
    "valid_age_type": "cast(AGE as int) == AGE",
    "valid_year_type": "cast(YEAR as int) == YEAR",
    "valid_caseid_type": "cast(CASEID as long) == CASEID",
    "valid_educ_values": "EDUC >= -9",
    "valid_ethnic_values": "ETHNIC >= -9",
    "valid_race_values": "RACE >= -9",
    "valid_gender_values": "GENDER >= -9",
    "valid_sphservice_values": "SPHSERVICE >= -9",
    "valid_cmpservice_values": "CMPSERVICE >= -9",
    "valid_opiservice_values": "OPISERVICE >= -9",
    "valid_rtcservice_values": "RTCSERVICE >= -9",
    "valid_ijsservice_values": "IJSSERVICE >= -9",
    "valid_mh1_values": "MH1 >= -9",
    "valid_mh2_values": "MH2 >= -9",
    "valid_mh3_values": "MH3 >= -9",
    "valid_sub_values": "SUB >= -9",
    "valid_marstat_values": "MARSTAT >= -9",
    "valid_smised_values": "SMISED >= -9",
    "valid_sap_values": "SAP >= -9",
    "valid_employ_values": "EMPLOY >= -9",
    "valid_detnlf_values": "DETNLF >= -9",
    "valid_veteran_values": "VETERAN >= -9",
    "valid_livarag_values": "LIVARAG >= -9",
    "valid_nummhs_values": "NUMMHS >= -9",
    "valid_traustref_values": "TRAUSTREFLG >= -9",
    "valid_anxiety_values": "ANXIETYFLG >= -9",
    "valid_adhd_values": "ADHDFLG >= -9",
    "valid_conduct_values": "CONDUCTFLG >= -9",
    "valid_delirdem_values": "DELIRDEMFLG >= -9",
    "valid_bipolar_values": "BIPOLARFLG >= -9",
    "valid_depress_values": "DEPRESSFLG >= -9",
    "valid_odd_values": "ODDFLG >= -9",
    "valid_pdd_values": "PDDFLG >= -9",
    "valid_person_values": "PERSONFLG >= -9",
    "valid_schizo_values": "SCHIZOFLG >= -9",
    "valid_alcsub_values": "ALCSUBFLG >= -9",
    "valid_otherdis_values": "OTHERDISFLG >= -9",
    "valid_statefip_values": "STATEFIP >= -9",
    "valid_division_values": "DIVISION >= -9",
    "valid_region_values": "REGION >= -9",
    "valid_demographic_strata": "demographic_strata IS NOT NULL AND demographic_strata != ''",
    "valid_strataIndex": "strataIndex IS NOT NULL AND cast(strataIndex as double) == strataIndex",
}

gold_validation = {
    "non_negative_age": "AGE >= 0 or AGE == -9",
    "valid_age_type": "cast(AGE as int) == AGE",
    "valid_year_type": "cast(YEAR as int) == YEAR",
    "valid_caseid_type": "cast(CASEID as long) == CASEID",
    "valid_educ_values": "EDUC >= -9",
    "valid_ethnic_values": "ETHNIC >= -9",
    "valid_race_values": "RACE >= -9",
    "valid_gender_values": "GENDER >= -9",
    "valid_sphservice_values": "SPHSERVICE >= -9",
    "valid_cmpservice_values": "CMPSERVICE >= -9",
    "valid_opiservice_values": "OPISERVICE >= -9",
    "valid_rtcservice_values": "RTCSERVICE >= -9",
    "valid_ijsservice_values": "IJSSERVICE >= -9",
    "valid_mh1_values": "MH1 >= -9",
    "valid_mh2_values": "MH2 >= -9",
    "valid_mh3_values": "MH3 >= -9",
    "valid_sub_values": "SUB >= -9",
    "valid_marstat_values": "MARSTAT >= -9",
    "valid_smised_values": "SMISED >= -9",
    "valid_sap_values": "SAP >= -9",
    "valid_employ_values": "EMPLOY >= -9",
    "valid_detnlf_values": "DETNLF >= -9",
    "valid_veteran_values": "VETERAN >= -9",
    "valid_livarag_values": "LIVARAG >= -9",
    "valid_nummhs_values": "NUMMHS >= -9",
    "valid_traustref_values": "TRAUSTREFLG >= -9",
    "valid_anxiety_values": "ANXIETYFLG >= -9",
    "valid_adhd_values": "ADHDFLG >= -9",
    "valid_conduct_values": "CONDUCTFLG >= -9",
    "valid_delirdem_values": "DELIRDEMFLG >= -9",
    "valid_bipolar_values": "BIPOLARFLG >= -9",
    "valid_depress_values": "DEPRESSFLG >= -9",
    "valid_odd_values": "ODDFLG >= -9",
    "valid_pdd_values": "PDDFLG >= -9",
    "valid_person_values": "PERSONFLG >= -9",
    "valid_schizo_values": "SCHIZOFLG >= -9",
    "valid_alcsub_values": "ALCSUBFLG >= -9",
    "valid_otherdis_values": "OTHERDISFLG >= -9",
    "valid_statefip_values": "STATEFIP >= -9",
    "valid_division_values": "DIVISION >= -9",
    "valid_region_values": "REGION >= -9",
    "valid_nummhs_normalized": "NUMMHS_normalized is not null",
    "valid_nummhs_standardized": "NUMMHS_standardized is not null",
    "valid_gender_mapped": "GENDER_mapped is not null",
    "valid_race_mapped": "RACE_mapped is not null",
    "valid_marstat_mapped": "MARSTAT_mapped is not null",
    "valid_employ_mapped": "EMPLOY_mapped is not null",
    "valid_ethnic_mapped": "ETHNIC_mapped is not null",
    "valid_caseid_int": "cast(CASEID_int as int) == CASEID_int",
}
